add basic UI
ijeomaodinko/OOP-school-library pull request #5
Opened 2022-10-07 20:31 UTC by ijeomaodinko

Create a app.rb file that will serve as your console app entry-point. It should have methods that do the following:
List all books.
List all people.
Create a person (teacher or student, not a plain Person).
Create a book.
Create a rental.
List all rentals for a given person id.
In your main.rb define the entry point, this will be a method called main that is invoked at the end of your file. This method should do the following:
Present the user with a list of options to perform.
Lets users choose an option.
If needed, ask for parameters for the option.
Have a way to quit the app.

2022-10-07 23:15 UTC, OLIPLICHE requested changes
Hi @ijeomaodinko, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Linter is green (the last commit have a green check mark (✅)) 👏
- README file is descriptive 👏
- Commit messages are meaningful 👏 👏
- Gitflow is correctly used (Pull Request is made from the feature branch into the dev branch) 👏

## Required Changes ♻️

- [ ] Please make sure your school library console app behaves in the same way as the [example video](https://www.youtube.com/watch?v=vkkgrhD6aXQ) provided for you

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-07 23:15 UTC, OLIPLICHE commented on app.rb
> +      @people << Student.new('unknown', age, name, permission)
- [ ] Please Check your code and solve this mistake. I see a kind of typo `chomps` in line 55. kindly check well.
![Capture](https://user-images.githubusercontent.com/63972670/194672879-12325c60-a224-4bde-ab37-d2a35b4bdc95.JPG)

2022-10-07 23:15 UTC, OLIPLICHE commented on app.rb
> +      teacher << Teacher.new(specialization, age, name)
- [ ] Please Check your code and solve this mistake. 
![Capture](https://user-images.githubusercontent.com/63972670/194673315-a4e10d68-b87d-4e36-ba89-17991c0c521d.JPG)

2022-10-07 23:15 UTC, OLIPLICHE commented on app.rb
> +    puts "Book created successfully \n"
- [ ] Please Check your code and solve this mistake.
- [ ] 
![Capture](https://user-images.githubusercontent.com/63972670/194673850-1fe2447f-81dd-4524-94f9-ef53a93d6017.JPG)

- [ ] Please [Open this Link to get a Hint](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/console_apps.md#console-app-entry-point). Maybe it gonna help

2022-10-08 01:15 UTC, 1GORDON requested changes
##
## Hi @ijeomaodinko ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] Kindly go over the functionality of your UI, and make sure it works as intended before you submit it again. You may check out the [video](https://www.youtube.com/watch?v=vkkgrhD6aXQ&ab_channel=EmiliaAndrzejewska) provided by the previous reviewer and try to make your design behave in a similar way.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-08 01:15 UTC, 1GORDON commented on app.rb
> +end
Great job @ijeomaodinko 🤝

- [ ] The UI still has some issues. Kindly make sure you can select rentals efficiently.
![list rentals](https://user-images.githubusercontent.com/63917725/194679975-274c9847-f0f0-436c-bace-cdfade6b0aac.PNG)

2022-10-08 01:15 UTC, 1GORDON commented on app.rb
> +  def create_rental
Great job @ijeomaodinko 🤝

- [ ] Kindly make sure the create rental method works as expected. At the moment option 5 selects books which is not the expected behavior.
![create-rental](https://user-images.githubusercontent.com/63917725/194680192-2a80b152-570f-4c0f-a6f9-8cd3d4ce3d0c.PNG)

2022-10-08 03:13 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-08 03:23 UTC, merged